const ANAUTHORUZED_REQUEST_401 = require('./ANAUTHORUZED_REQUEST_401');
const ERROR_404_NOTFOUND = require('./ERROR_404_NOTFOUND');
const ERROR_IN_REQUATION = require('./ERROR_IN_REQUATION');
const ERROR_403_PERMISSION = require('./ERROR_403_PERMISSION');
const CODE_CONFLICT = require('./CODE_CONFLICT');

module.exports = {
  ANAUTHORUZED_REQUEST_401,
  ERROR_404_NOTFOUND,
  ERROR_IN_REQUATION,
  ERROR_403_PERMISSION,
  CODE_CONFLICT,
};
